### ISSUE TITLE
Parte 8 - Bibliografia

### ISSUE THREAD

**Issue by fabianoshimura** [rafaelcorreiapoli/relatorio#10]
Numerical Analysis. NINTH EDITION. Richard L. Burden.
Atratores Estranhos de Lorenz Marcelo Viana IMPA - Rio de Janeiro
J. Sotomayor, Lições de Equações Diferenciais Ordinárias, Projeto Euclides, Rio de
Janeiro: IMPA, 1979.
E. N. Lorenz, "Deterministic Nonperiodic Flow," J. Atmos. Sci. 20, 130-41 (1963). Reprinted in [Cvitanovic, 1984].
Chaos and Nonlinear Dynamics: an introduction for scientists and enginers", Robert C. Hilborn

**Comment by rafaelcorreiapoli** [comment]
Done!
