### ISSUE TITLE
Parte 5 - Splines again

### ISSUE THREAD

**Issue by fabianoshimura** [rafaelcorreiapoli/relatorio#12]
Nesta seção, vamos utilizar o spline como etapa de pós processamento, no intuito de observar a forma da curva gerada pelas tabelas de 1 a 7 (na qual 0<t<2). Para tanto, foi utilizada a função "splin" do SciLab, para cada variável x, y e z em relação ao tempo. Tal implementação e seu código estão mais bem explicados no Apêndice A - Splines.
Vale ressaltar que o código gerou uma curva suave (Spline cúbica) com os pontos iniciais e finais para o período em questão. O Spline é um método de boa precisão na interpolação de pontos, para uma boa visualização de gráficos gerados por tabelas.

**Comment by rafaelcorreiapoli** [comment]
Este é o texto que vai no 5) antes dos gráficos ?

**Comment by fabianoshimura** [comment]
ISSO

**Comment by rafaelcorreiapoli** [comment]
Coloquei
