### ISSUE TITLE
Parte 2: EDOs e Condições iniciais

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [rafaelcorreiapoli/relatorio#4]
- [x] Colocar 3 equações
- [x] Valor das constantes
- [x] Condições inicias: explicar que se uma tiver condição inciial diferente das demais, o sistema entra em Estado Caótico

**Comment by fabianoshimura** [comment]
As equações na forma diferencial são:
-> eq1
->eq2
->eq3

em que a \sigma se chama o número de Prandtl e a \rho se chama o número de Rayleigh. Todos os \sigma, \rho, \beta > 0, mas usualmente \sigma = 10, \beta = 8/3, enquanto \rho varia. O sistema exibe comportamento caótico para \rho = 28 mas tem órbitas periódicas para outros valores de \rho.

**Comment by rafaelcorreiapoli** [comment]
@fabianoshimura  são essas aqui?
https://pt.wikipedia.org/wiki/Atractor_de_Lorenz

**Comment by rafaelcorreiapoli** [comment]
O que que eu coloco de Condições iniciais ?

**Comment by fabianoshimura** [comment]
Isso isso isso
Eh o suficiente

Fabiano M. Shimura
Vivo: (11)97225-9100
Tim: (11)94847-8919

**Comment by fabianoshimura** [comment]
Condicoes iniciais

x0 = 0
y0 = 0
z0 = 10

Fabiano M. Shimura
Vivo: (11)97225-9100
Tim: (11)94847-8919

**Comment by rafaelcorreiapoli** [comment]
Coloquei

**Comment by rafaelcorreiapoli** [comment]
Tá correta essa parte? vê o pdf

**Comment by fabianoshimura** [comment]
verei....

**Comment by fabianoshimura** [comment]
Temos que escrever que as condicoes iniciais sao arbitrarias, e foram escolhidas para o estudo do efeito caotico.

No caso, para demonstrar o efeito caotico, basta que um dos termos deve ser diferente dos demais.

Para condicoes iniciais nulas, x0 = 0, y0 = 0, z0 = 0,  o sistema permanece em repouso.

**Comment by rafaelcorreiapoli** [comment]
Coloquei
