### ISSUE TITLE
Parte 4: Análise de Resultados

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [rafaelcorreiapoli/relatorio#6]
- [x] Gráficos: Explicar que só tem 1 para cada faixa de tempo pois os resultados das duas metodologias foram iguais
- [x] Análise em texto
- [x] Tabela

**Comment by rafaelcorreiapoli** [comment]
@fabianoshimura Tem como gerar a tabela com menos casas decimais? ta zuando tudo aqui

**Comment by fabianoshimura** [comment]
Faltou colocar a parte de verificação por solução manufaturada


Solucao manufaturada:

x(t) = -(y/10)*e^(-10t) + (y/10)
y(t) = (-28x + xz)*e^(-t) + 28x -xz
z(t) = 10 + x*y*t - (8/3)y*t

**Comment by rafaelcorreiapoli** [comment]
Aonde exatamente?

**Comment by rafaelcorreiapoli** [comment]
Coloquei dentro de Euler, numa seção "Solução Manufaturada"

**Comment by fabianoshimura** [comment]
4.3 - Solução Manufaturada

A solução manufaturada tem como objetivo comparar o comportamento da curva obtida pelos dois métodos mediante a uma solução particular (no caso, para x0 = 0, y0 = 0 e z0 = 0). Para cada discretização no intervalo em questão (0<t<2), podemos plotar os gráficos abaixo e observar claramente a preferência pelo método de Runge-Kutta para a solução das EDOs, uma vez que ela convergirá muito mais rapidamente para a solução.

**Comment by rafaelcorreiapoli** [comment]
Coloquei

**Comment by fabianoshimura** [comment]
Foi mal escrevi errado!

(no caso, para x0 = 0, y0 = 0 e z0 = 10)

*era z0 = 10!

**Comment by fabianoshimura** [comment]
@rafaelcorreiapoli Como eu disse no email...
Para todos os gráficos da borboleta, na parte 4.1, escrever como legenda:

 "Gráfico (x,y) em vermelho, e (x,z) em azul" para todos os gráficos.

**Comment by rafaelcorreiapoli** [comment]
Arrumei o z0 e coloquei a explicação do que é cada cor

**Comment by rafaelcorreiapoli** [comment]
Dá uma olhada ae, se tiver tudo certo pode fechar

**Comment by fabianoshimura** [comment]
Beleza.

Soh falta na parte 4.3 arrumar:

Gráfico (t,x) , (t,y) e (t,z)

**Comment by fabianoshimura** [comment]
Acabou.
Vc nao acha que tem muito espaço em branco?
Se não, pode fechar.

**Comment by rafaelcorreiapoli** [comment]
Não entendi o que é pra arrumar em 4.3

**Comment by rafaelcorreiapoli** [comment]
Tem só isso de espaço em branco
![espacobranco](https://cloud.githubusercontent.com/assets/12840136/14272241/896ee45a-fad7-11e5-9014-d15696dd7d30.png)

**Comment by fabianoshimura** [comment]
Eh soh trocar o x pelo t.
Pq eh uma funcao de x em funcao de t.
O tempo eh continuo.

**Comment by fabianoshimura** [comment]
Esta assim: (x,t) , (y,t) e (z,t)

Eh pra ficar assim: (t,x) , (t,y) e (t,z)

**Comment by rafaelcorreiapoli** [comment]
No item 4.3 não tem isso

**Comment by rafaelcorreiapoli** [comment]
no 4.3 tinha "Gráfico de (x, t)" e eu mudei pra "Gráfico de (t, x)"

**Comment by fabianoshimura** [comment]
era isso...!

 Date: Mon, 4 Apr 2016 22:41:55 -0700

**Comment by rafaelcorreiapoli** [comment]
Então da uma olhada ai se tá certo, subi já

**Comment by fabianoshimura** [comment]
acabei de ver. Tah certo!
Pode fechar

Date: Mon, 4 Apr 2016 22:42:44 -0700
