### ISSUE TITLE
Parte 5: Spline

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [rafaelcorreiapoli/relatorio#7]
- [x] Explicar: usamos a tabela para chegar na equação por Spline
- [x] Gráficos
- [x] Explicação do Algoritmo

**Comment by fabianoshimura** [comment]
Jah esta feito :)

**Comment by rafaelcorreiapoli** [comment]
Coloquei os gráficos na Parte 5) Splines
Explicação e algoritmo ficaram no Apêndice
@fabianoshimura correto ?

**Comment by fabianoshimura** [comment]
Isso. Boa.
