### ISSUE TITLE
Parte 6 - Conclusão

### ISSUE THREAD

**Issue by fabianoshimura** [rafaelcorreiapoli/relatorio#9]
- [x] Conclusao

**Comment by fabianoshimura** [comment]
O escopo deste trabalho consistiu na resolução das três equações diferenciais de Lorentz através de métodos numéricos aprendidos na disciplina. Para tanto, utilizamos o método de Euler explícito pela sua facilidade do algoritmo e pela obtenção de uma boa aproximação inicial, na qual podemos comparar com o gráfico da solução manufaturada. Em seguida, implementamos o método de Runge-Kutta Clássico, e já observamos uma aproximação muito mais consistente e próxima do esperado, já que este possui convergência de quarta ordem. 
O estudo destas equações, além de ter despertado o interesse na aplicação de métodos numéricos para sua resolução, tem forte aplicação em diversas áreas no estudo da teoria do caos como mencionado anteriormente, apesar do modelo ser derivado de uma simplificação de equações mais complexas.

**Comment by rafaelcorreiapoli** [comment]
Check!
